FRINXio/fm-workflows

startup.sh

Add wait after restarting micros container

---

workflows/Mount_from_inventory.json

Fix Mount_from_Inventory

---

startup.sh

Move start of Write_data_to_netconf_testool to startup.sh

---

workers/lldp_worker.py
workers/platform_worker.py
workers/unified_worker.py

Uniconfig transactions

---

workflows/Post_to_Slack.json

Fix Post_to_Slack workflow

---

workflows/Build_read_store_LLDP_topology.json
workflows/Create_L2VPN_P2P_OC_uniconfig.json
workflows/Execute_and_read_rpc_cli_device_from_inventory.json

Fixed Workflows from tests

---

workers/inventory_worker.py
workflows/Add_cli_command_template_to_inventory.json
workflows/Add_cli_device_to_inventory.json
workflows/Add_netconf_device_to_inventory.json
workflows/Read_journal_cli_device.json

Added missing workflows and fix tasks inputs

---

workflows/Export_LLDP_topology.json

Added Export_LLDP_topology workflow

---

workflows/Create_loopback_all_in_uniconfig.json
workflows/Create_loopback_all_in_unified.json
workflows/Mount_all_from_inventory.json

Added #bool to workflows

---

README.md
cypress.json
cypress/integration/00kibana_fm_init_spec.js
cypress/integration/01mount_device_spec.js
cypress/integration/02mount_all_devices_spec.js
cypress/integration/03unmount_incompat_devs_spec.js
cypress/integration/10create_loopback_spec.js
cypress/integration/11create_wrkfl_check_lpbck_spec.js
cypress/integration/12check_loopback.spec.js
cypress/integration/20lacp_spec.js
cypress/integration/30lldp_build_spec.js
cypress/integration/31lldp_kibana_check_spec.js
cypress/integration/32lldp_export_spec.js
cypress/integration/33lldp_graphviz_spec.js
cypress/integration/40obtain_data_spec.js
cypress/integration/41obtain_data_kibana_check_spec.js
cypress/integration/50commands_save_spec.js
cypress/integration/51commands_kibana_check_spec.js
cypress/integration/52commands_execute_spec.js
cypress/integration/60add_device_spec.js
cypress/integration/61add_device_kibana_check_spec.js
cypress/integration/63mount_device_spec.js
cypress/integration/64unmount_device_spec.js
cypress/integration/65add_device_kibana_delete_spec.js
cypress/integration/90unmount_all_devices_spec.js
cypress/integration/README.md
cypress/plugins/index.js
cypress/support/commands.js
cypress/support/index.js

add e2e tests for FRINX-machine

---

workflows/Create_loopback_all_in_uniconfig.json
workflows/Create_loopback_all_in_unified.json
workflows/Execute_all_from_cli_update_inventory.json
workflows/Read_components_all_from_unified.json
workflows/Read_components_update_inventory.json

replace tabs with spaces in workflow definitions

---

startup.sh

fix empty configuration (404) for netconf-testtool

---

cypress/integration/02mount_all_devices_spec.js

fix Expected to find content: 'Details of Dynamic_fork' but never did.

---

cypress/integration/01mount_device_spec.js

reconcile to get configuration and prevent 404 code

---

cypress/integration/11create_wrkfl_check_lpbck_spec.js
cypress/integration/64unmount_del_device_spec.js

fix delete workflow (satisfy confirmation window)

---

workflows/Create_loopback_all_in_uniconfig.json
workflows/Create_loopback_all_in_unified.json
workflows/Dynamic_fork.json
workflows/Execute_all_from_cli_update_inventory.json
workflows/Link_aggregation.json
workflows/Mount_all_from_inventory.json
workflows/Read_components_all_from_unified.json
workflows/Read_components_all_from_unified_update_inventory.json
workflows/Read_interfaces_all_from_unified.json

Needs to be merged together: https://github.com/FRINXio/frinx-workflow-ui/pull/47
Signed-off-by: Adam Chmara <adam.chmara1@gmail.com>

Change of workflows including dynamic fork

---

cypress/integration/55commands_execute_spec.js

fix display of dynamically forked subworkflow

---

cypress/integration/02mount_all_devices_spec.js
cypress/integration/10create_loopback_spec.js
cypress/integration/30lldp_build_spec.js
cypress/integration/53commands_execute_spec.js
cypress/integration/55commands_execute_spec.js

make the cypress tests more robust

---

cypress/integration/02mount_all_devices_spec.js
cypress/integration/10create_loopback_spec.js

fix broken navigation via clicking to log

---

docker-compose.host.yml

add missing volume declaration

---

.gitmodules

add submodule sample-topology/cli-testtool

---

README.md
docker-compose.host.yml
startup.sh
wait_for_it.sh

fix host mode networking

---

workers/unified_worker.py
workflows/Read_components_all_from_unified_update_inventory.json
workflows/Read_components_update_inventory.json

Read components fixes

---

cypress/integration/00kibana_fm_init_spec.js
cypress/integration/01mount_device_spec.js
cypress/integration/02mount_all_devices_spec.js
cypress/integration/03unmount_incompat_devs_spec.js
cypress/integration/10create_loopback_spec.js
cypress/integration/11create_wrkfl_check_lpbck_spec.js
cypress/integration/12check_loopback.spec.js
cypress/integration/20lacp_spec.js
cypress/integration/30lldp_build_spec.js
cypress/integration/32lldp_export_spec.js
cypress/integration/40obtain_data_spec.js
cypress/integration/50commands_save_spec.js
cypress/integration/52commands_execute_spec.js
cypress/integration/53commands_execute_spec.js
cypress/integration/54cmd_exec_kibana_check_spec.js
cypress/integration/55commands_execute_spec.js
cypress/integration/60add_device_spec.js
cypress/integration/63mount_device_spec.js
cypress/integration/64unmount_del_device_spec.js
cypress/integration/70unmount_all_devices_spec.js
cypress/integration/71UniConfig_Netconf_Testool_spec.js
cypress/integration/74Unmount_Netconf_Testool_spec.js
cypress/integration/75UniConfig_Netconf_Testool_spec.js
cypress/integration/78Unmount_Netconf_Testool_spec.js
cypress/integration/79UniConfig_Netconf_Testool_spec.js
cypress/integration/90unmount_all_devices_spec.js
cypress/support/commands.js
sample-topology/Dockerfile

fix cypress tests after separation of UI

---

cypress/integration/01mount_device_spec.js
cypress/integration/03unmount_incompat_devs_spec.js
cypress/integration/10create_loopback_spec.js
cypress/integration/12check_loopback.spec.js
cypress/integration/63mount_device_spec.js
cypress/integration/71UniConfig_Netconf_Testool_spec.js
cypress/integration/75UniConfig_Netconf_Testool_spec.js
cypress/integration/79UniConfig_Netconf_Testool_spec.js
cypress/integration/90unmount_all_devices_spec.js
cypress/support/commands.js

fix cypress tests

---

.github/workflows/docker-publish.yml

Docker img publish for sample-topology and micros-demo

Add gh action for docker img publish

---

demo-workflows/workers/cli_worker.py
demo-workflows/workers/netconf_worker.py

- added array to node in mount requests
Signed-off-by: Martin Sunal <msunal@frinx.io>

fixed mount requests

---

demo-workflows/workers/cli_worker.py

Added execute task to be used in future workflows
Signed-off-by: Matej Matkuliak <mmatkuliak@frinx.io>

Added execute task definition to cli_worker

---

README.md
composefiles/swarm-fm-workflows.yml
startup.sh

based on changes in https://github.com/FRINXio/FRINX-machine/pull/188 PR

Add option for change uniconfig service name

---

demo-workflows/workflows/IOSXR_Upgrade.json
demo-workflows/workflows/IOSXR_Upgrade_loopTask.json

Added workflow that upgrades IOS version + do_while task that is used as sub-workflow in the upgrade workflow
Signed-off-by: Matej Matkuliak <mmatkuliak@frinx.io>

IOSXR Upgrade workflow + loop workflow

---

demo-workflows/workflows/Uniconfig_policy_filter_XR.json

Workflow that returns interface name based on description that user provides. Chosen policy-map is then applied on that interface. Configured for IOS XR devices.
Signed-off-by: Matej Matkuliak <mmatkuliak@frinx.io>

Added policy filter wf for XR devices

---

.github/workflows/docker-publish.yml
composefiles/swarm-fm-workflows.yml
sample-topology/README.md
sample-topology/build_st_docker_image.sh
startup.sh

- Delete volumes from ST composefile
- Put yang schemas into ST docker image

Delete volume from sample topology composefile

---

sample-topology/README.md
sample-topology/build_st_docker_image.sh
startup.sh

In case of downloading FM worlfkows as zip without .git folder download also cli testtool before building docker image

Sample topology fix clitestool build

---

demo-workflows/workflows/Create_L2VPN_P2P_OC_uniconfig.json

-fixed failing decision task
-removed secont transaction and task related to it
Signed-off-by: Matej Matkuliak <mmatkuliak@frinx.io>

Edit of L2VPN_P2P_OC_uniconfig task

---

README.md
composefiles/swarm-fm-workflows.yml
demo-workflows/devices/cli_device_data.csv
demo-workflows/workers/importDevices.py
demo-workflows/workers/main.py
sample-topology/build_st_docker_image.sh
sample-topology/scripts/run_netconf_devices/generate_devices_setup.py
startup.sh
teardown.sh

add some features like teardown.sh and make some refactor
add feature that only simulated devices will show in device inventory

Customize device inventory to run only simulated devices

---

composefiles/swarm-fm-workflows.yml
demo-workflows/requirements.txt

Bump docker image versions

---

composefiles/swarm-fm-workflows.yml
demo-workflows/devices/cli_device_data.csv
demo-workflows/devices/cli_saos_device_data.csv
demo-workflows/workflows/Create_loopback_all_in_uniconfig.json

Added label "CREATE_LOOPBACK_DEMO" to devices which support create_loopback demo workflow. Also added this label as pre-filled value for this workflow.

add labels to devices and create loopback wf edit

---

demo-workflows/workers/main.py
demo-workflows/workers/topology_discovery_worker.py
demo-workflows/workflows/Arangodb_create_backup_and_delete_old_backups.json

- add functions to a new worker 'topology_discovery_worker' arangodb_create_backup and arangodb_delete_backups
- add WF Arangodb_create_backup_and_delete_old_backups

Add topology discovery arango backup db wf
